import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import baysRouter from "./bays";
import customersRouter from "./customers";
import bookingsRouter from "./bookings";
import membershipsRouter from "./memberships";
import membershipPlansRouter from "./membership-plans";
import tenantRouter from "./tenant";
import posOrdersRouter from "./pos-orders";
import passesRouter from "./passes";
import passPlansRouter from "./pass-plans";
import discountCodesRouter from "./discount-codes";
import schedulesRouter from "./schedules";
import loyaltyPointsRouter from "./loyalty-points";
import notificationTemplatesRouter from "./notification-templates";
import legalDocumentsRouter from "./legal-documents";
import formsRouter from "./forms";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(dashboardRouter);
router.use(baysRouter);
router.use(customersRouter);
router.use(bookingsRouter);
router.use(membershipsRouter);
router.use(membershipPlansRouter);
router.use(tenantRouter);
router.use(posOrdersRouter);
router.use(passesRouter);
router.use(passPlansRouter);
router.use(discountCodesRouter);
router.use(schedulesRouter);
router.use(loyaltyPointsRouter);
router.use(notificationTemplatesRouter);
router.use(legalDocumentsRouter);
router.use(formsRouter);

export default router;
